version: '3.3'
services:

  DB_postgreSQL:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'user345'
      POSTGRES_PASSWORD: 'password345'
      POSTGRES_DB: 'MathGameDB'
    ports:
      - '5432:5432'

  app:
   build: .
   environment:
    WAIT_HOSTS: DB_postgreSQL:5432
   ports:
     - '8080:8000'